USE Tutorica;

insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (1, 'Nariko', 'Drewery', 'University of the Faroe Islands', '794-940-2089', 'ndrewery0@pbs.org', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 27, 12.0, 5.29, 63.48);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (2, 'Mannie', 'Saltwell', 'Akrofi-Christaller Institute of Theeology, Mission and  Culture', '142-959-1284', 'msaltwell1@list-manage.com', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 33, 12.0, 3.33, 39.96);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (3, 'Byram', 'Handrock', 'Universidad de Oriente', '211-957-7462', 'bhandrock2@furl.net', 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 50, 12.0, 5.77, 69.24);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (4, 'Jacintha', 'Mease', 'Université Dakar Bourguiba', '225-963-5779', 'jmease3@shareasale.com', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 1, 12.0, 5.66, 67.92);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (5, 'Ivar', 'Compson', 'Burdwan University', '396-865-5723', 'icompson4@epa.gov', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 46, 12.0, 2.19, 26.28);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (6, 'Reinaldos', 'Brundle', 'Siberian Academy of Public Services', '627-525-6753', 'rbrundle5@gravatar.com', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 56, 12.0, 1.21, 14.52);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (7, 'Bliss', 'Pezey', 'Facultés Universitaires Notre-Dame de la Paix', '774-869-4577', 'bpezey6@usda.gov', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 47, 12.0, 4.8, 57.6);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (8, 'Baldwin', 'Shee', 'Universidade Gregorio Semedo', '404-792-7252', 'bshee7@reverbnation.com', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', 59, 12.0, 3.17, 38.04);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (9, 'Clifford', 'McElwee', 'Universidade do Porto', '843-266-7087', 'cmcelwee8@bloglines.com', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 98, 12.0, 1.32, 15.84);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (10, 'Reynard', 'Ponter', 'Universidad Autónoma de San Luis Potosí', '130-396-0211', 'rponter9@pen.io', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 49, 12.0, 2.33, 27.96);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (11, 'Fidel', 'Baldocci', 'Fachhochschule Ludwigshafen, Hochschule für Wirtschaft', '656-258-9746', 'fbaldoccia@github.com', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 55, 12.0, 4.17, 50.04);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (12, 'Emlen', 'Barsam', 'European Academy of Arts in Warsaw', '783-257-8874', 'ebarsamb@va.gov', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 53, 12.0, 4.0, 48.0);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (13, 'Nikolos', 'Westwater', 'Moscow Institute of Physics and Technology', '768-972-7165', 'nwestwaterc@who.int', 'Quisque ut erat.', 47, 12.0, 2.47, 29.64);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (14, 'Harrison', 'Grimsell', 'Bowling Green State University', '609-759-5960', 'hgrimselld@apple.com', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 83, 12.0, 1.66, 19.92);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (15, 'Reggy', 'Tumasian', 'Technical University of Denmark', '907-235-4854', 'rtumasiane@imdb.com', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 91, 12.0, 1.01, 12.12);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (16, 'Myles', 'Facchini', 'I-Shou University', '996-364-7789', 'mfacchinif@paypal.com', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 87, 12.0, 5.76, 69.12);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (17, 'Syman', 'Davson', 'American Film Institute Center for Advanced Film and Television Studies', '777-650-5717', 'sdavsong@w3.org', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 39, 12.0, 2.01, 24.12);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (18, 'Tamiko', 'Pearse', 'Universidad Autónoma de Las Américas', '654-588-7960', 'tpearseh@twitpic.com', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 18, 12.0, 5.31, 63.72);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (19, 'Harvey', 'Bertenshaw', 'Planwel University', '538-506-0594', 'hbertenshawi@gnu.org', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 53, 12.0, 1.44, 17.28);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (20, 'Desmond', 'Louedey', 'University of Illinois at Springfield', '315-326-7471', 'dlouedeyj@hc360.com', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 82, 12.0, 4.65, 55.8);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (21, 'Stevena', 'Nutkin', 'Makhanlal Chaturvedi National University of Journalism and Communication', '436-731-2420', 'snutkink@webs.com', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 12, 12.0, 1.81, 21.72);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (22, 'Kermit', 'Paramor', 'Universidad Politécnica de Valencia', '902-999-1743', 'kparamorl@wired.com', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 50, 12.0, 2.3, 27.6);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (23, 'Briant', 'Sketch', 'Technion - Israel Institute of Technology', '575-379-7682', 'bsketchm@eepurl.com', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 34, 12.0, 2.22, 26.64);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (24, 'Goldy', 'Eltone', 'Sebha University', '467-655-1009', 'geltonen@weather.com', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 76, 12.0, 1.03, 12.36);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (25, 'Nelle', 'Balassa', 'St. Norbert College', '215-534-6953', 'nbalassao@technorati.com', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 61, 12.0, 4.43, 53.16);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (26, 'Willis', 'Bradock', 'University of Oradea', '659-998-3604', 'wbradockp@oaic.gov.au', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 4, 12.0, 1.37, 16.44);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (27, 'Kaitlynn', 'Hackey', 'Instituto Superior de Tecnologias Avançadas - ISTEC', '456-577-4206', 'khackeyq@eepurl.com', 'Ut tellus.', 65, 12.0, 5.75, 69.0);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (28, 'Alano', 'Akett', 'Universidad Autónoma del Estado de Morelos', '924-611-8081', 'aakettr@latimes.com', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 34, 12.0, 5.6, 67.2);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (29, 'Lanie', 'Puller', 'Faculté Polytechnique de Mons', '862-655-7116', 'lpullers@webnode.com', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 32, 12.0, 2.84, 34.08);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (30, 'Harri', 'Kemmett', 'National Dairy Research Institute', '968-149-8017', 'hkemmettt@joomla.org', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 89, 12.0, 4.45, 53.4);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (31, 'Sunny', 'Clarycott', 'Universidad Autónoma de Ciudad Juárez', '887-337-5224', 'sclarycottu@livejournal.com', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 40, 12.0, 2.4, 28.8);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (32, 'Brit', 'Godbald', 'Universidad Centroamericana de Ciencias Empresariales (UCEM)', '424-391-0256', 'bgodbaldv@prweb.com', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 88, 12.0, 1.7, 20.4);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (33, 'Lynett', 'MacClancey', 'Kanda University of International Studies', '748-212-3324', 'lmacclanceyw@acquirethisname.com', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 72, 12.0, 4.0, 48.0);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (34, 'Guillermo', 'Henaughan', 'Sohar University', '899-313-1547', 'ghenaughanx@sciencedirect.com', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 64, 12.0, 3.33, 39.96);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (35, 'Katti', 'Tacon', 'Trinity Western University', '112-339-7996', 'ktacony@usda.gov', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 18, 12.0, 3.57, 42.84);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (36, 'Kerrin', 'Marjoram', 'Xi''an Jiaotong University', '853-803-3792', 'kmarjoramz@blogspot.com', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 23, 12.0, 3.62, 43.44);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (37, 'Celina', 'Plowes', 'Baldwin-Wallace College', '286-426-1072', 'cplowes10@blogs.com', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 42, 12.0, 3.08, 36.96);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (38, 'Winnah', 'Fawlkes', 'Université de M''sila', '745-235-0785', 'wfawlkes11@networkadvertising.org', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 25, 12.0, 5.3, 63.6);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (39, 'Zelma', 'Sinkins', 'Bellarmine College', '897-260-1064', 'zsinkins12@tiny.cc', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 99, 12.0, 1.76, 21.12);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (40, 'Tabatha', 'Olennikov', 'Institut National Supérieur de Formation Agro-Alimentaire', '470-628-2132', 'tolennikov13@nature.com', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 25, 12.0, 4.88, 58.56);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (41, 'Cullen', 'Winston', 'Mokwon University Taejon', '257-321-9532', 'cwinston14@weibo.com', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 45, 12.0, 5.53, 66.36);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (42, 'Liesa', 'Jeynes', 'Central University for Nationalities', '672-653-5129', 'ljeynes15@hao123.com', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 98, 12.0, 2.17, 26.04);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (43, 'Judi', 'O''Hare', 'Université de Jendouba', '989-218-8725', 'johare16@4shared.com', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 44, 12.0, 2.9, 34.8);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (44, 'Danila', 'Pratten', 'Institut Teknologi Adhi Tama Surabaya', '666-575-1925', 'dpratten17@tuttocitta.it', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 16, 12.0, 5.92, 71.04);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (45, 'Hephzibah', 'Tankus', 'University of Tennessee - Martin', '327-850-5998', 'htankus18@joomla.org', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 9, 12.0, 1.15, 13.8);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (46, 'Sascha', 'Annable', 'Université de Pau et des Pays de l''Adour', '466-763-2258', 'sannable19@dagondesign.com', 'Vestibulum sed magna at nunc commodo placerat.', 99, 12.0, 5.62, 67.44);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (47, 'Christoper', 'Gordon', 'Instituto Universitario de Estudios Navales y Marítimos', '994-261-1864', 'cgordon1a@ning.com', 'Vivamus in felis eu sapien cursus vestibulum.', 11, 12.0, 1.26, 15.12);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (48, 'Traver', 'Binge', 'University of Sassari', '215-110-6915', 'tbinge1b@moonfruit.com', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 91, 12.0, 2.96, 35.52);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (49, 'Fernando', 'Greensted', 'Moscow State University of Commerce', '498-355-6886', 'fgreensted1c@cisco.com', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 18, 12.0, 5.38, 64.56);
insert into items (Id, firstname, lastname, Enterprisename, phonenumber, email, entdescription, age, annual_turnover_usd, course, annual_turnover_uah) values (50, 'Pam', 'Wapples', 'Institut Textile et Chimique de Lyon', '899-880-0211', 'pwapples1d@jugem.jp', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 26, 12.0, 3.21, 38.52);




