openapi: '3.0.2'
info:
  title: Tutorica API
  version: '1.0'
servers:
  - url: http://192.168.56.101:7020/api/v1
  - url: http://192.168.56.101:7020/api/v2
paths:
  /enterprises:
    get:
      tags:
          - enterprises
      operationId: GetAllEnterprises
      summary: Get all enterprises
      description: Get all enterprises
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Enterprises'
  /advertisement:
    post:
      tags:
      - advertisement
      operationId: PostAdvertisement
      summary: Post advertisement
      description: Post advertisement
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Advertisement'
      responses:
        '201':
          description: Created
  /getcourse:
    get:
      tags:
      - getcourse
      operationId: GetCourse
      summary: Get course
      description: Get Course
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                date:
                  type: string
                currency:
                  type: string
                course:
                  type: float
      responses:
        '200':
          description: OK
  /feedback:
    post:
      tags:
      - feedback
      operationId: PostFeedback
      summary: Post feedback
      description: Post feedback
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                email:
                  type: string
                msgText:
                  type: string
      responses:
        '201':
          description: Created        
      
components:
  schemas:
    Enterprises:
      type: object
      properties:
        id:
          type: integer
        firstName: 
          type: string
        lastName: 
          type: string
        enterpriseName:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        entDescription:
          type: string
        age:
          type: integer
        a_t_USD:
          type: numeric  
        course:
          type: numeric
        a_t_UAH:
          type: numeric     
    Advertisement:
      type: object
      properties:
        firstName: 
          type: string
        lastName: 
          type: string
        enterpriseName:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        entDescription:
          type: string
        age:
          type: integer
        a_t_USD:
          type: numeric  
        course:
          type: numeric
        a_t_UAH:
          type: numeric     
    Course:
      type: object
      properties:
        date:
          type: string
        currency:
          type: string
        course:
          type: float          
